const mainList = [
    {name: "Brigade", index: "1"},
    {name: "Glyph", index: "2"},
    {name: "Goodworld", index: "3"},
    {name: "Infaera", index: "4"},
    {name: "Kondor", index: "5"},
    {name: "Lennkaz", index: "6"},
    {name: "Lt. Ouroumov", index: "7"},
    {name: "Hikiller", index: "8"},
    {name: "PixelGMS", index: "9"},
    {name: "Pasadena", index: "10"},
    {name: "Punch", index: "11"},
    {name: "Serenity", index: "12"},
    {name: "Traveller", index: "13"},
    {name: "Yunzhong Hou", index: "14"},
    {name: "Aldar", index: "15"},
    {name: "Maximus", index: "16"},
    {name: "Om1cr0n", index: "17"},
    {name: "Graev", index: "18"}
]
  
const childList =[
    {index: "1", path: 'custom/brigadewormV6/index', size: '0', name: "Worm V6"},
    {index: "2", path: 'custom/glyphwormV6/index', size: '0', name: "Worm V6"},
    {index: "2", path: 'glyphmha', size: '2', name: "MHA"},
    {index: "3", path: 'goodworldmysticmartialarts', size: '4', name: "Mystic Martial Arts"},
    {index: "4", path: 'infaeraharrypotter', size: '1', name: "Harry Potter"},
    {index: "4", path: 'infaeraopisekai', size: '6', name: "OP Isekai"},
    {index: "5", path: 'kondorhp', size: '10', name: "Harry Potter"},
    {index: "6", path: 'lennkazjedi', size: '75', name: "SW Jedi"},
    {index: "6", path: 'lennkazsithlord', size: '4', name: "SW Sith Lord"},
    {index: "6", path: 'lennkazwarlord', size: '16', name: "SW Warlord"},
    {index: "7", path: 'ltouroumovwormv6', size: '45', name: "Worm V6"},
    {index: "10", path: 'pasadenalg', size: '21', name: "Living God"},
    {index: "10", path: 'pasadenawormv3', size: '12', name: "Worm V3"},
    {index: "11", path: 'punchgamer', size: '1', name: "Interactive Gamer"},
    {index: "11", path: 'punchnaruto', size: '30', name: "Naruto"},
    {index: "12", path: 'serenityhp', size: '57', name: "Harry Potter"},
    {index: "13", path: 'travellerpsychic', size: '13', name: "Psychic"},
    {index: "14", path: 'custom/YunzhongHouLuminarium/index', size: '0', name: "Luminarium"},
    {index: "9", path: 'pixelgmsrwby1.2', size: '4', name: "RWBY 1.2"},
    {index: "9", path: 'pixelgmsrwby1.1', size: '10', name: "RWBY 1.1"},
    {index: "9", path: 'pixelgmsfatebeta', size: '5', name: "Fate Beta"},
    {index: "15", path: 'aldartech', size: '2', name: "Tech Transdimensional"},
    {index: "13", path: 'travellerworm', size: '13', name: "Worm"},
    {index: "8", path: 'hikillerpcxenon', size: '2', name: "Power Creator Xenon"},
    {index: "16", path: 'custom/maximusworm/index', size: '0', name: "Worm"},
    {index: "17", path: 'Om1cr0nrwby', size: '4', name: "RWBY"},
    {index: "18", path: 'graevmm', size: '15', name: "Multiverse Mage"},
    {index: "17", path: 'Om1cr0ndemigod', size: '33', name: "Demigod"}
]